# @package _group_
bagging_temperature: 1
bootstrap_type: Bayesian
l2_leaf_reg: 1
learning_rate: 0.6
loss_function: Logloss
max_depth: 5
n_estimators: 300
random_strength: 0.5
verbose: true
use_best_model: True
