# @package _group_
bagging_temperature: 5
bootstrap_type: Bayesian
l2_leaf_reg: 3
learning_rate: 0.2
loss_function: Logloss
max_depth: 6
n_estimators: 150
random_strength: 0.2
verbose: true
use_best_model: True
