# hydra:
#   job:
#     # env_copy:
#     #   - HOST # Service host
#     #   - PORT # Service port
#     env_set:
#       HOST: "0.0.0.0"
#       PORT: "8000"

# MODEL_PATH = "

# defaults:
  # - model: catboost
  # - feature: feature
  # - data_load: data_load
  # - data_split: data_split
  # - general: general_local
